"""observations and daily normals

Revision ID: 02cdb2612d0c
Revises: f8fd1b06fa98
Create Date: 2026-09-04 12:10:27.034360
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '02cdb2612d0c'
down_revision: str | None = 'f8fd1b06fa98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_normals',
    sa.Column('cell_id', sa.String(length=20), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('tmax_c', sa.Float(), nullable=False),
    sa.Column('tmin_c', sa.Float(), nullable=False),
    sa.Column('precip_mm', sa.Float(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cell_id', 'month', 'day')
    )
    op.create_table('observations',
    sa.Column('cell_id', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tmax_c', sa.Float(), nullable=True),
    sa.Column('tmin_c', sa.Float(), nullable=True),
    sa.Column('tmean_c', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cell_id', 'date')
    )
    op.create_index('ix_observations_wet_days', 'observations', ['cell_id', 'date'], unique=False, postgresql_using='btree', postgresql_where=sa.text('precip_mm >= 0.2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_wet_days', table_name='observations', postgresql_using='btree', postgresql_where=sa.text('precip_mm >= 0.2'))
    op.drop_table('observations')
    op.drop_table('daily_normals')
    # ### end Alembic commands ###
